// Names from "Captain Underpants and the Perilous Plot of Professor Poopypants" by Dav Pilkey

var data1 = {
	'A': 'Stinky',
	'B': 'Lumpy',
	'C': 'Buttercup',
	'D': 'Gidget',
	'E': 'Crusty',
	'F': 'Greasy',
	'G': 'Fluffy',
	'H': 'Cheeseball',
	'I': 'Chim-Chim',
	'J': 'Poopsie',
	'K': 'Flunky',
	'L': 'Booger',
	'M': 'Pinky',
	'N': 'Zippy',
	'O': 'Goober',
	'P': 'Doofus',
	'Q': 'Slimy',
	'R': 'Loopy',
	'S': 'Snotty',
	'T': 'Falafel',
	'U': 'Dorky',
	'V': 'Squeezit',
	'W': 'Oprah',
	'X': 'Skipper',
	'Y': 'Dinky',
	'Z': 'Zsa-Zsa',
};

var data2 = {
	'A': 'Diaper',
	'B': 'Toilet',
	'C': 'Giggle',
	'D': 'Bubble',
	'E': 'Girdle',
	'F': 'Barf',
	'G': 'Lizard',
	'H': 'Waffle',
	'I': 'Cootie',
	'J': 'Monkey',
	'K': 'Potty',
	'L': 'Liver',
	'M': 'Banana',
	'N': 'Rhino',
	'O': 'Burger',
	'P': 'Hamster',
	'Q': 'Toad',
	'R': 'Gizzard',
	'S': 'Pizza',
	'T': 'Gerbil',
	'U': 'Chicken',
	'V': 'Pickle',
	'W': 'Chuckle',
	'X': 'Tofu',
	'Y': 'Gorilla',
	'Z': 'Stinker',
};

var data3 = {
	'A': 'head',
	'B': 'mouth',
	'C': 'face',
	'D': 'nose',
	'E': 'tush',
	'F': 'breath',
	'G': 'pants',
	'H': 'shorts',
	'I': 'lips',
	'J': 'honker',
	'K': 'butt',
	'L': 'brain',
	'M': 'tushie',
	'N': 'chunks',
	'O': 'hiney',
	'P': 'biscuits',
	'Q': 'toes',
	'R': 'buns',
	'S': 'fanny',
	'T': 'sniffer',
	'U': 'sprinkels',
	'V': 'kisser',
	'W': 'squirt',
	'X': 'humperdink',
	'Y': 'brains',
	'Z': 'juice',
};