// Fake Shakespearean-sounding nickname data

var insultGenerator = function(key1, key2, key3) {
	$('p').html("Thy epitaph shall read: <strong>Thou " + data1[key1]  + data2[key2] + data3[key3] + '!</strong>');
};

var data1 = {
	'A': 'Churlish',
	'B': 'Beslubbering',
	'C': 'Clay-brained',
	'D': 'Fusty',
	'E': 'Stale',
	'F': 'Frothy',
	'G': 'Beemish',
	'H': 'Fool-born',
	'I': 'Impudent',
	'J': 'Malmsey-nosed',
	'K': 'Stinking',
	'L': 'Lumpish',
	'M': 'Whining',
	'N': 'Beastliest',
	'O': 'Wayward',
	'P': 'Pestilent',
	'Q': 'Purblind',
	'R': 'Rank',
	'S': 'Swarthy',
	'T': 'Tedious',
	'U': 'Sinful',
	'V': 'Villainous',
	'W': 'Whoreson',
	'X': 'Whimpled',
	'Y': 'Vain',
	'Z': 'Wrathful',
};

var data2 = {
	'A': 'Reeking',
	'B': 'Spur-galled',
	'C': 'Unwashed',
	'D': 'Dunnest',
	'E': 'Tottering',
	'F': 'Brainsickly',
	'G': 'Poisonous',
	'H': 'Lily-livered',
	'I': 'Idle-headed',
	'J': 'Brain-dead',
	'K': 'Fishified',
	'L': 'Dissembling',
	'M': 'Malecontent',
	'N': 'Bunch-backed',
	'O': 'Onion-eyed',
	'P': 'Worm-eaten',
	'Q': 'Fen-sucked',
	'R': 'Rump-fed',
	'S': 'Sinful',
	'T': 'Shard-born',
	'U': 'Treacherous',
	'V': 'Qualling',
	'W': 'Wool-sack',
	'X': 'Flesh mongering',
	'Y': 'Cowardly',
	'Z': 'Belching',
};

var data3 = {
	'A': ' Infection',
	'B': ' Baggage',
	'C': ' Capon',
	'D': ' Maggot',
	'E': ' Canker-blossom',
	'F': ' Fool',
	'G': ' Gudgeon',
	'H': ' Harpy',
	'I': ' Gnat',
	'J': ' Jolt-head',
	'K': ' Rascal',
	'L': ' Minnow',
	'M': ' Malt-worm',
	'N': ' Bastard-son',
	'O': ' Pigeon-egg',
	'P': ' Pinpot',
	'Q': ' Butt-shaft',
	'R': ' Hugger-mugger',
	'S': ' Sour-face',
	'T': ' Tallow-catch',
	'U': ' Urchin',
	'V': ' Villain',
	'W': ' Moldwarp',
	'X': ' Wagtail',
	'Y': ' Coward',
	'Z': ' Wretch',
};